#!/usr/bin/env python3
"""Builds the GeckoView extension's two content scripts from the GeckoView bridge and the shared
MRBD shim (app/src/main/assets/mrbd-shim.js). Run it after changing either.

- mrbd-ext/page.js: the bridge and the shim, run by Gecko in the page's own world
  (`"world": "MAIN"`), so a page's Content Security Policy can't block them. Injecting them as an
  inline <script> from content.js was blocked on pages with a strict CSP (measured on a Google
  sign-in page and on m.youtube.com: "The page's settings blocked an inline script").
- mrbd-ext/content.js: the isolated content script, relaying window messages between the page
  and background.js.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
assets = root / 'app/src/main/assets'
bridge = (assets / 'mrbd-ext/page-bridge.js').read_text()
shim = (assets / 'mrbd-shim.js').read_text()

page = ('// Generated by scripts/gen-gecko-content.py from mrbd-ext/page-bridge.js and mrbd-shim.js.\n'
        "// Runs at document_start in the page's own world (manifest: \"world\": \"MAIN\").\n"
        + bridge + shim)
(assets / 'mrbd-ext/page.js').write_text(page)

content = '''// Generated by scripts/gen-gecko-content.py.
// Runs at document_start in an isolated world, next to page.js in the page's own world: relays
// window messages between the page and background.js.
(function () {
  window.addEventListener('message', (event) => {
    const message = event.data && event.data.__mrbdToHost;
    if (message && event.source === window) browser.runtime.sendMessage(message);
  });
  // Opens the app's port for this page, so canGoBack and Back reach it.
  browser.runtime.sendMessage({ type: 'hello', url: location.href });
  browser.runtime.onMessage.addListener((message) => {
    // The background sends a message to the tab it's for only; one meant for an app (its
    // configuration, which may hold secrets) also names its origin and reaches only that page.
    if (message && message.origin && message.origin !== location.origin) return;
    window.postMessage({ __mrbdFromHost: message }, location.origin === 'null' ? '*' : location.origin);
  });
})();
'''
(assets / 'mrbd-ext/content.js').write_text(content)
print('wrote', assets / 'mrbd-ext/page.js', 'and', assets / 'mrbd-ext/content.js')
