#!/usr/bin/env python3
"""Builds app/src/main/assets/mrbd-ext/content.js from the GeckoView bridge and the shared
MRBD shim (app/src/main/assets/mrbd-shim.js). Run it after changing either."""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
assets = root / 'app/src/main/assets'
bridge = (assets / 'mrbd-ext/page-bridge.js').read_text()
shim = (assets / 'mrbd-shim.js').read_text()
content = '''// Generated by scripts/gen-gecko-content.py from mrbd-ext/page-bridge.js and mrbd-shim.js.
// Runs at document_start in an isolated world: puts the host bridge and the MRBD shim into
// the page's own world, then relays window messages between the page and background.js.
(function () {
  const code = %s;
  const script = document.createElement('script');
  script.textContent = code;
  (document.head || document.documentElement).appendChild(script);
  script.remove();
  window.addEventListener('message', (event) => {
    const message = event.data && event.data.__mrbdToHost;
    if (message && event.source === window) browser.runtime.sendMessage(message);
  });
  // Opens the app's port for this page, so canGoBack and Back reach it.
  browser.runtime.sendMessage({ type: 'hello', url: location.href });
  browser.runtime.onMessage.addListener((message) => {
    // The background sends a message to the tab it's for only; one meant for an app (its
    // configuration, which may hold secrets) also names its origin and reaches only that page.
    if (message && message.origin && message.origin !== location.origin) return;
    window.postMessage({ __mrbdFromHost: message }, location.origin === 'null' ? '*' : location.origin);
  });
})();
''' % json.dumps(bridge + shim)
(assets / 'mrbd-ext/content.js').write_text(content)
print('wrote', assets / 'mrbd-ext/content.js')
